# Generated by Django 5.2.13 on 2026-04-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_documento', models.IntegerField(blank=True, null=True)),
                ('n_documento', models.IntegerField(blank=True, null=True)),
                ('nombres_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('numero_telefonico', models.BigIntegerField(blank=True, null=True)),
                ('id_direccion', models.IntegerField(blank=True, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('estado_cuenta', models.CharField(blank=True, max_length=8, null=True)),
                ('foto_url', models.CharField(blank=True, db_column='Foto_url', max_length=255, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('id_ciudad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_documento', models.IntegerField(blank=True, null=True)),
                ('n_documento', models.IntegerField(blank=True, null=True)),
                ('nombres_funcionario', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos_funcionario', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('numero_telefonico', models.BigIntegerField(blank=True, null=True)),
                ('id_direccion', models.IntegerField(blank=True, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('id_rol', models.IntegerField(blank=True, null=True)),
                ('estado_cuenta', models.CharField(blank=True, max_length=8, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialSesionesClientes',
            fields=[
                ('id_historial_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('estado_sesion', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'historial_sesiones_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialSesionesFuncionarios',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('id_funcionario', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('estado_sesion', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'historial_sesiones_funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=100)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesPermisos',
            fields=[
                ('id_rol_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('id_rol', models.IntegerField()),
                ('id_permiso', models.IntegerField()),
            ],
            options={
                'db_table': 'roles_permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_documentos',
                'managed': False,
            },
        ),
    ]
